import React from 'react';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import $api from '../../api/http';
import axios from 'axios';

const flattenObject = (obj, parentKey = '', result = {}) => {
    for (let key in obj) {
        if (obj.hasOwnProperty(key)) {
            const newKey = parentKey ? `${parentKey}.${key}` : key;

            if (typeof obj[key] === 'object' && obj[key] !== null) {
                flattenObject(obj[key], newKey, result);
            } else {
                result[newKey] = obj[key];
            }
        }
    }
    return result;
};

const flattenData = (data) => {
    return data.map(item => flattenObject(item));
};


function ReportButton({ data }) {

    const username = localStorage.getItem("user")
    const chatId = localStorage.getItem("chatId")

    const exportToExcel = async () => {
        if (data && data.length > 0) {
            const flattenedData = flattenData(data);

            const worksheet = XLSX.utils.json_to_sheet(flattenedData);

            const workbook = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');

            const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });

            const file = new Blob([excelBuffer], { type: 'application/octet-stream' });
            saveAs(file, `${window.location.pathname == "/" ? "Companies" : window.location.pathname}` + '.xlsx');
            await $api.post("/history", { username: username, date: new Date().toISOString(), nametable: window.location.pathname == "/" ? "Companies" : window.location.pathname })


            if (chatId !== null) {
                const formData = new FormData();
                formData.append("chat_id", chatId);
                formData.append("document", new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${window.location.pathname == "/" ? "Companies" : window.location.pathname}.xlsx`);
                formData.append("caption", `Report generated by ${username}`);

                await axios.post(`https://api.telegram.org/bot7372336509:AAGM-U4JrELrmp1UgfxpxVtJ662Q0aOTnHk/sendDocument`, formData, {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                });
            }
        } else {
            alert("No Data Yet");
        }
    };

    return (
        <button style={{
            padding: 10,
            border: "none",
            borderRadius: "4px",
            backgroundColor: "#534e9f",
            color: "white",
            fontWeight: "600",
            cursor: "pointer",
            fontSize: "16px",
            position: "absolute",
            right: "20px"
        }} onClick={exportToExcel}>Install Report Excel</button>
    )
}

export default ReportButton;
